# Copyright 2021 Gravitational, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '2'
services:
  etcd0:
    image: quay.io/coreos/etcd:v3.4.13
    ports:
      - 2379
    networks:
      etcd:
        ipv4_address: 172.11.1.1      
    volumes:
      - /tmp/data/0:/etcd_data
      - ./certs:/certs
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd0
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - https://172.11.1.1:2379
      - -listen-client-urls
      - https://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - https://172.11.1.1:2380
      - -listen-peer-urls
      - https://0.0.0.0:2380
      - -initial-cluster
      - etcd0=https://172.11.1.1:2380,etcd1=https://172.11.1.2:2380,etcd2=https://172.11.1.3:2380
      - --trusted-ca-file=/certs/ca-cert.pem      
      - --cert-file=/certs/server-cert.pem
      - --key-file=/certs/server-key.pem
      - --peer-cert-file=/certs/server-cert.pem
      - --peer-key-file=/certs/server-key.pem
      - --peer-trusted-ca-file=/certs/ca-cert.pem
      - --client-cert-auth
      - --peer-client-cert-auth            
  etcd1:
    image: quay.io/coreos/etcd:v3.4.13
    ports:
      - 2379
    networks:
      etcd:
        ipv4_address: 172.11.1.2      
    volumes:
      - /tmp/data/1:/etcd_data
      - ./certs:/certs
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd1
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - https://172.11.1.2:2379
      - -listen-client-urls
      - https://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - https://172.11.1.2:2380
      - -listen-peer-urls
      - https://0.0.0.0:2380
      - -initial-cluster
      - etcd0=https://172.11.1.1:2380,etcd1=https://172.11.1.2:2380,etcd2=https://172.11.1.3:2380
      - --trusted-ca-file=/certs/ca-cert.pem      
      - --cert-file=/certs/server-cert.pem
      - --key-file=/certs/server-key.pem
      - --peer-cert-file=/certs/server-cert.pem
      - --peer-key-file=/certs/server-key.pem
      - --peer-trusted-ca-file=/certs/ca-cert.pem
      - --client-cert-auth
      - --peer-client-cert-auth                  
  etcd2:
    image: quay.io/coreos/etcd:v3.4.13
    networks:
      etcd:
        ipv4_address: 172.11.1.3
    ports:
      - 2379
    volumes:
      - /tmp/data/2:/etcd_data
      - ./certs:/certs
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd2
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - https://172.11.1.3:2379
      - -listen-client-urls
      - https://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - https://172.11.1.3:2380
      - -listen-peer-urls
      - https://0.0.0.0:2380
      - -initial-cluster
      - etcd0=https://172.11.1.1:2380,etcd1=https://172.11.1.2:2380,etcd2=https://172.11.1.3:2380
      - --trusted-ca-file=/certs/ca-cert.pem      
      - --cert-file=/certs/server-cert.pem
      - --key-file=/certs/server-key.pem
      - --peer-cert-file=/certs/server-cert.pem
      - --peer-key-file=/certs/server-key.pem
      - --peer-trusted-ca-file=/certs/ca-cert.pem
      - --client-cert-auth
      - --peer-client-cert-auth                  
networks:
  etcd:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.11.1.0/16
        ip_range: 172.11.1.0/24
        gateway: 172.11.1.254
