# Copyright 2021 Gravitational, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '2'
services:
  # The configure container starts, generates a config, writes it to
  # /etc/teleport/teleport.yaml and then immediately exits.
  configure:
    image: quay.io/gravitational/teleport:6
    container_name: teleport-configure
    entrypoint: /bin/sh
    hostname: localhost
    command: -c "if [ ! -f /etc/teleport/teleport.yaml ]; then teleport configure > /etc/teleport/teleport.yaml; fi"
    volumes:
      - ./teleport/config:/etc/teleport

  # This container depends on the config written by the configure container above, so it
  # sleeps for a second on startup to allow the configure container to run first.
  teleport:
    image: quay.io/gravitational/teleport:6
    container_name: teleport
    entrypoint: /bin/sh
    hostname: localhost
    command: -c "sleep 1 && /usr/bin/dumb-init teleport start -c /etc/teleport/teleport.yaml"
    ports:
      - "3023:3023"
      - "3025:3025"
      - "3080:3080"
    volumes:
      - ./teleport/config:/etc/teleport
      - ./teleport/data:/var/lib/teleport
    depends_on:
      - configure

  #
  # one-sshd is a single-node Teleport cluster called "one" (runs all 3 roles: proxy, auth and node)
  #
  one-sshd:
    image: teleport:latest
    container_name: one-sshd
    command: /usr/bin/start-sshd.sh
    env_file: env.file
    mem_limit: 300m
    volumes:
      - ./sshd/pam.d/ssh:/etc/pam.d/ssh
      - ./sshd/etc/ssh/sshd_config:/etc/ssh/sshd_config
      - certs:/mnt/shared/certs
    networks:
      teleport:
        ipv4_address: 172.10.1.21
