# Copyright 2021 Gravitational, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is a naive deployment example
# to highlight the most important upgrade points:
#
# * Ordering of the upgrades
# * Scale down/ups of auth servers during upgrades
#
# Things to be done before this is production ready
#
# * Backup/restore of database before auth server upgrades
# * Collaboration with load balancers to drain connections
# * Health checks post auth server upgrade
# * Rollbacks and restores from backups
#
- hosts: "auth, proxy, node"
  name: Download new version of teleport to auth and proxies
  become: yes
  remote_user: admin
  become_method: sudo
  tasks:

    - include: vars.yaml

    - name: Copy gops to target box (for debugging)
      when: gops_path is defined
      block:
      - copy:
          src: "{{gops_path}}"
          dest: /usr/local/bin
          mode: 0755

    - name: Copy binaries from local directory
      when: teleport_path is defined
      block:
      - copy:
          src: "{{teleport_path}}/teleport"
          dest: /usr/local/bin

      - copy:
          src: "{{teleport_path}}/tctl"
          dest: /usr/local/bin

    - name: Copy binaries from official repository
      when: teleport_version is defined
      block:
      - name: Download and unpack new version of teleport
        get_url:
          url: https://get.gravitational.com/teleport/{{teleport_version}}/teleport-ent-v{{teleport_version}}-linux-amd64-bin.tar.gz
          dest: /tmp/teleport-ent-v{{teleport_version}}-linux-amd64-bin.tar.gz
      - name: Unpack teleport binaries
        unarchive:
          extra_opts: ['--strip-components=1', '--show-stored-names']
          exclude:
            - "examples/*"
            - "README.md"
            - "VERSION"
            - "INSTALL"
            - "CHANGELOG"
          src: /tmp/teleport-ent-v{{teleport_version}}-linux-amd64-bin.tar.gz
          dest: /usr/local/bin
          remote_src: yes
          owner: "{{ 'root' if 'node' in group_names else 'teleport' }}"
          group: "{{ 'root' if 'node' in group_names else 'teleport' }}"


# Scale down all auth servers but the first one
# The new auth server will run migrations, so during upgrade
# there should be only one auth server available
- hosts: "auth[1:]"
  name: Scale down all auth servers but one
  become: yes
  remote_user: admin
  become_method: sudo
  tasks:

    - include: vars.yaml

    - name: Stop teleport
      service:
        name: teleport
        state: stopped

- hosts: "auth[0]"
  name: Restart the first auth server
  become: yes
  remote_user: admin
  become_method: sudo
  tasks:

    - include: vars.yaml

    - name: Restart teleport
      service:
        name: teleport
        state: restarted

- hosts: "auth[1:]"
  name: Restart the rest of auth servers
  become: yes
  remote_user: admin
  become_method: sudo
  tasks:

    - include: vars.yaml

    - name: Restart teleport
      service:
        name: teleport
        state: restarted


- hosts: "proxy"
  name: Restart the proxies
  become: yes
  remote_user: admin
  become_method: sudo
  tasks:

    - include: vars.yaml

    - name: Restart teleport
      service:
        name: teleport
        state: restarted

- hosts: "node"
  name: Restart the nodes
  become: yes
  remote_user: admin
  become_method: sudo
  tasks:

    - include: vars.yaml

    - name: Restart teleport
      service:
        name: teleport
        state: restarted
