# Copyright 2021 Gravitational, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: {{ template "teleport.fullname" . }}
  labels:
{{ include "teleport.labels" . | indent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if and .Values.service.loadBalancerSourceRanges (eq .Values.service.type "LoadBalancer") }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
  ports:
{{- range $key, $value := .Values.service.ports }}
{{- if or (not $.Values.config.highAvailability) (and ($.Values.config.highAvailability) (not (eq $key "authssh"))) }}
  - name: {{ $key }}
{{ toYaml $value | indent 4 }}
{{- end }}
{{- end }}
{{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.Values.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
{{- end }}
  selector:
    app: {{ template "teleport.name" . }}
    release: {{ .Release.Name }}
{{- if .Values.config.highAvailability }}
    auth: noauth
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "teleport.fullname" . }}auth
  labels:
{{ include "teleport.labels" . | indent 4 }}
{{- if .Values.config.authService.labels }}
{{ toYaml .Values.config.config.authService.labels | indent 4 }}
{{- end }}
{{- if .Values.config.authService.annotations }}
  annotations:
{{ toYaml .Values.config.authService.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.config.authService.type }}
{{- if and .Values.config.authService.loadBalancerSourceRanges (eq .Values.config.authService.type "LoadBalancer") }}
  loadBalancerSourceRanges:
{{ toYaml .Values.config.authService.loadBalancerSourceRanges | indent 4 }}
{{- end }}
  ports:
    - name: authssh
      port: {{ .Values.ports.authssh.containerPort }}
      targetPort: {{ .Values.ports.authssh.containerPort }}
      protocol: TCP
{{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.Values.config.authService.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.config.authService.externalTrafficPolicy }}"
{{- end }}
  selector:
    app: {{ template "teleport.name" . }}
    release: {{ .Release.Name }}
    auth: hasauth
{{- end }}

